[base]
IsDebug=false

[gin]
Addr="0.0.0.0:8081"
IsDebug=false
Mode="debug"

[logger]
# 参考 go-logger
Target="console"

[rabbitmq.default]
dsn="amqp://guest:guest@localhost:5672/"
Qos=10
Heartbeat=10
Vhost="/test"
Channel="test_channel"
Exchange="test_exchange"
ExchangeType="fanout"
Queue="test_queue"
Route="test_route"

[gorm.default]
dsn="user:password@/dbname?charset=utf8&parseTime=True&loc=Local"